### ISSUE TITLE
ID: 12 Kategori: Fysisk netværks opsætning

### ISSUE THREAD

**Issue by NicolaiMartini** [KEA-E24-B9-IOT1/E24-B9-IoT1#12]
# Krav: 
Gruppen Justerer deres tidligere designede netværk ud fra følgende specifikationer: 
Ip adresser jf. RFC 1918 til Router/default gateway, en hardware firewall, et trådløst Access punkt (WAP) 10 servere, 10 printere og 30 klienter, og udvidelsesmulighed på 10-30% -med hvad der kommer af ændringer i IoT- projektet

# Accepttest: 
Der forelægger fulddokumentation i form af: 
1. IP-plan 
2. Adressetabel
3. Diagram over fysisk topologi -Topologi udført i Packet tracer 
Hvis dette er til stede, er det accepteret.

**Comment by NickaNii** [comment]
Har leget rundt med Simon, og vi har fået det hele til at virke (minus "clouden" men jaja) - har smidt den i Waiting til, at Kenneth har sagt ja til den.
