### ISSUE TITLE
ID: 2 Kategori: UX

### ISSUE THREAD

**Issue by NicolaiMartini** [KEA-E24-B9-IOT1/E24-B9-IoT1#2]
# Krav: 
På den lokale konsol, Educaboard, skal vises hastighed, retning, længde- og breddegrad, batteristatus og temperatur

# Accepttest: 
1. Batteri skal være fuldt opladet 
2. Løsningen tændes 
3. Konsollen observeres samtidig med, at brugeren cykler rundt i fem minutter. Imens observeres hastighed, retning, længde- og breddegrad og sammenlignes med identiske data fra en mobiltelefon. 
- Hvis data for smartcyklen er inden for 5 % af mobiltelefonen, er kravet opfyldt.

**Comment by HelligeGiffel** [comment]
Its working! Vi har ikke lavet accept-test, men der skrives ting på Display. ID2_main, bliver konverteret til en fil med en enkelt funktion vi kan kalde fra vores Main
