### ISSUE TITLE
ID: 6 Kategori: Signallering

### ISSUE THREAD

**Issue by NicolaiMartini** [KEA-E24-B9-IOT1/E24-B9-IoT1#6]
# Krav: 
Bremselys skal lyse når der bremses over en valgfri negativ acceleration

# Accepttest: 
1. Batteri skal være fuldt opladet 
2. Løsningen tændes 
3. Når der bremses over en valgfri negativ acceleration, skal et bremselys tændes. 
- Sker det, er kravet bestået.

**Comment by NicolaiMartini** [comment]
Læg venligst i "Waiting" efter den er testet.
Når alle kode-dele er sat op, kan vi efterfølgende raffinere dem.

**Comment by HelligeGiffel** [comment]
Krav 6 er lavet og pushet til git. Fungere vist efter hensigten
