### ISSUE TITLE
Flowchart ID 7

### ISSUE THREAD

**Issue by NicolaiMartini** [KEA-E24-B9-IOT1/E24-B9-IoT1#75]
Visning af den forventede resttid løsningen kan bruges. 
Visningen skal være på lokal konsol, Educaboard, og på Thingsboard

**Comment by NicolaiMartini** [comment]
Opsat.
Tjek venligst.
Kommenter evt. ændringer eller spørgsmål.
Ellers ryk til Done.

**Comment by HelligeGiffel** [comment]
Hvis vi anvender gennemsnitsforbruget over 3 timer, så er flowchartet her perfekt. Ellers kan vi altid bygge videre med INA219?
Jeg har ingen rettelser
